# -*- mode: Python -*-

# For more on Extensions, see: https://docs.tilt.dev/extensions.html
#load('ext://restart_process', 'docker_build_with_restart')

custom_build(
  'quay.io/raffaelespazzoli/keycloak.x',
  'buildah bud -t $EXPECTED_REF -f ./Dockerfile .  && buildah push $EXPECTED_REF $EXPECTED_REF',
  entrypoint=['/opt/keycloak/keycloak.x-12.0.4/bin/kc.sh'],
  deps=['./Dockerfile'],
  skips_local_docker=True,
)

allow_k8s_contexts(['keycloak/api-tmp-raffa-demo-red-chesterfield-com:6443/raffa','keycloak/api-cluster1-acm-aws-cluster-demo-red-chesterfield-com:6443/kube:admin'])
k8s_yaml(['keycloak.x-statefulset.yaml'])